---

apiVersion: v1
kind: Pod
metadata: 
  name: kubia-manual
  labels:
    env: prod
    app: kubia-manual
spec:
  containers:
    - image: luksa/kubia
      name: kubia
      ports: 
        - containerPort: 8080
          protocol: TCP
      livenessProbe:
        httpGet:
          path: / 
          port: 8080

