---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  username: {{ required "dbUsername must be defined" .Values.dbUsername | b64enc | quote }}
  password: {{ required "dbPassword must be defined" .Values.dbPassword | b64enc | quote }}
  