---
 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node-app
          image: {{ .Values.imageRegistry }}/node-app:{{ .Values.appVersion }}
          ports:
            - port: {{ .Values.nodeApp.port }}
              containerPort: {{ .Values.nodeApp.port }}
          livenessProbe:
            httpGet:
              path: / 
              port: {{ .Values.nodeApp.port }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: POSTGRES_DB
              key: {{ .Values.postgres.dbName }}
            - name: PORT
              value: '{{ .Values.nodeApp.port }}'
            - name: POSTGRES_HOST
              value: $(POSTGRES_SERVICE_HOST)
            - name: POSTGRES_PORT
              value: $(POSTGRES_SERVICE_PORT)
          