---

apiVersion: v1
kind: Service
metadata: 
  name: {{ .Release.Name }}-node
spec:
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: node

---
 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: {{ .Release.Name }}-node-app
          image: eu.gcr.io/GCP_PROJECT_ID/node-app:latest
          ports:
            - containerPort: 8888
          livenessProbe:
            httpGet:
              path: / 
              port: 8888
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: PORT
              value: '8888'
            - name: POSTGRES_HOST
              value: $(POSTGRES_SERVICE_HOST)
            - name: POSTGRES_PORT
              value: $(POSTGRES_SERVICE_PORT)
              