---

apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: IfNotPresent
          ports:
            - name: psql
              port: {{ .Values.postgres.port }} 
              containerPort: 5432 
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: POSTGRES_DB
              key: {{ .Values.postgres.dbName }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-pv-claim
              subPath: data
  volumeClaimTemplates:
  - metadata:
      name: postgres-pv-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
          