---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  username: {{ .Values.postgresql.dbUsername | b64enc }}
  password: {{ .Values.postgresql.dbPassword | b64enc }}
  